import { useState } from 'react';
import { useData } from '../context/store';
import { Banknote } from 'lucide-react';
import { format, endOfMonth, isWeekend, subDays } from 'date-fns';
import { fr } from 'date-fns/locale';

const YEARS = [2025, 2026, 2027, 2028, 2029, 2030];
const MONTHS = Array.from({ length: 12 }, (_, i) => i); // 0-11

export const Salaries = () => {
    const { data, addTransaction, updateTransaction } = useData();
    const [selectedYear, setSelectedYear] = useState(new Date().getFullYear() < 2025 ? 2025 : new Date().getFullYear());

    // Ensure selected year is within range if not default
    if (!YEARS.includes(selectedYear) && selectedYear > 2030) setSelectedYear(2030);
    if (!YEARS.includes(selectedYear) && selectedYear < 2025) setSelectedYear(2025);

    const getSalaryTransaction = (monthIndex) => {
        return data.transactions.find(t => {
            const d = new Date(t.date);
            return d.getFullYear() === selectedYear &&
                d.getMonth() === monthIndex &&
                (t.category === 'Salaire' || t.description.toLowerCase().includes('salaire')) &&
                t.type === 'income';
        });
    };

    const handleSalaryChange = (monthIndex, value) => {
        const amount = parseFloat(value);
        if (isNaN(amount)) return;

        const existing = getSalaryTransaction(monthIndex);

        if (existing) {
            // Only update if amount changed
            if (Number(existing.amount) !== amount) {
                updateTransaction(existing.id, { amount });
            }
        } else {
            // Create new
            if (amount > 0) {
                // Calculate "Pay Day" (End of month, or previous Friday if weekend)
                let payDate = endOfMonth(new Date(selectedYear, monthIndex));
                if (isWeekend(payDate)) {
                    const day = payDate.getDay(); // 0 is Sun, 6 is Sat
                    payDate = subDays(payDate, day === 0 ? 2 : 1);
                }

                addTransaction({
                    description: `Salaire ${format(payDate, 'MMMM', { locale: fr })}`,
                    amount: amount,
                    type: 'income',
                    category: 'Salaire',
                    date: format(payDate, 'yyyy-MM-dd HH:mm'),
                    isAutoGenerated: false
                });
            }
        }
    };

    // Calculate total for the year
    const totalYear = MONTHS.reduce((acc, m) => {
        const t = getSalaryTransaction(m);
        return acc + (t ? Number(t.amount) : 0);
    }, 0);

    return (
        <div className="space-y-6 h-full flex flex-col">
            <div className="flex flex-col md:flex-row justify-between items-center gap-4 shrink-0">
                <div>
                    <h2 className="heading-lg mb-1">Salaires</h2>
                    <p className="text-slate-500">Gestion des revenus mensuels</p>
                </div>

                <div className="bg-white p-1 rounded-xl border border-slate-200 shadow-sm flex items-center">
                    {YEARS.map(year => (
                        <button
                            key={year}
                            onClick={() => setSelectedYear(year)}
                            className={`px-4 py-2 text-sm font-medium rounded-lg transition-all ${selectedYear === year
                                ? 'bg-slate-900 text-white shadow-md'
                                : 'text-slate-500 hover:text-slate-700 hover:bg-slate-50'
                                }`}
                        >
                            {year}
                        </button>
                    ))}
                </div>
            </div>

            <div className="bg-white rounded-2xl shadow-sm border border-slate-100 flex-1 flex flex-col overflow-hidden">
                {/* Header / Total */}
                <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
                    <div className="flex items-center gap-3">
                        <div className="p-2 bg-green-100 text-green-600 rounded-lg">
                            <Banknote size={24} />
                        </div>
                        <div>
                            <div className="text-xs font-semibold text-slate-500 uppercase tracking-wide">Total Annuel {selectedYear}</div>
                            <div className="text-2xl font-bold text-slate-900">€{totalYear.toLocaleString()}</div>
                        </div>
                    </div>
                </div>


                <div className="overflow-auto flex-1">

                    <div className='flex'>
                        <div className="px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Mois</div>
                        <div className="px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider">Montant (Net)</div>
                        <div className="px-6 py-3 text-xs font-semibold text-slate-500 uppercase tracking-wider text-right">Statut</div>
                    </div>

                    {MONTHS.map(monthIndex => {
                        const date = new Date(selectedYear, monthIndex, 1);
                        const transaction = getSalaryTransaction(monthIndex);
                        const amount = transaction ? transaction.amount : '';

                        return (
                            <div key={`${selectedYear}-${monthIndex}`} className="hover:bg-slate-50/50 transition-colors flex justify-between items-center">
                                <div className="py-2 w-1/3 px-6">
                                    <span className="font-medium text-slate-900 capitalize block">
                                        {format(date, 'MMMM', { locale: fr })}
                                    </span>
                                </div>
                                <div className="py-2 w-1/3 px-3">
                                    <div className="relative max-w-xs">
                                        <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 font-bold">€</span>
                                        {/* Key added to input to force re-render when year changes */}
                                        <input
                                            key={`input-${selectedYear}-${monthIndex}`}
                                            type="number"
                                            placeholder="0.00"
                                            defaultValue={amount}
                                            onBlur={(e) => handleSalaryChange(monthIndex, e.target.value)}
                                            className="pl-8 font-semibold text-slate-900 bg-white border-slate-200 focus:border-blue-500 focus:ring-blue-500/20 py-1.5"
                                        />
                                    </div>
                                </div>
                                <div className="py-2 w-1/3 text-right px-3">
                                    {transaction ? (
                                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                                            Enregistré
                                        </span>
                                    ) : (
                                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-amber-100 text-amber-800">
                                            En attente
                                        </span>
                                    )}
                                </div>
                            </div>
                        );
                    })}
                </div>
            </div>
        </div>
    );
};
